export const LOADING = 'LOADING';
export const LOAD_CHARACTERS_PAGE = 'LOAD_CHARACTERS_PAGE';
export const SET_CURR_PAGE = 'SET_CURR_PAGE';
export const SET_PAGES = 'SET_PAGES';
export const SET_DETAILS_CHARACTER = 'SET_DETAILS_CHARACTER';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DEL_FAVORITE = 'DEL_FAVORITE';
